added a python implementation of the interpolation search algorithm
SamareshMaiti16/PythonDSA pull request #21
Opened 2022-10-22 09:49 UTC by sumanta02

Added a python implementation of the interpolation search algorithm. Please check if the added code is up to the mark and working as intended.

Thank you :-)

2022-10-23 16:06 UTC, SamareshMaiti16 requested changes
You have done a good job. However I want to suggest a few modifications. Instead of asking for sorted inputs, include a sorting algo in your code.

2022-10-23 18:55 UTC, sumanta02 commented
I have added a heapsort sorting function to sort the user input data and then use interpolation search algorithm on the sorted input. Please check if the added code is up to the mark and working as intended.

Thank you :-)

2022-10-24 05:21 UTC, SamareshMaiti16 requested changes
Your Sorting works fine but the searching part is messed up. Please look into it.

2022-10-24 07:58 UTC, SamareshMaiti16 approved these changes

2022-10-24 07:58 UTC, merged